INSERT INTO categories (name) VALUES
('Eletrodomésticos'),
('Móveis e Decoração'),
('Ferramentas e Equipamentos'),
('Alimentos e Bebidas'),
('Roupas e Acessórios'),
('Eletrônicos e Gadgets'),
('Brinquedos e Jogos'),
('Materiais de Construção'),
('Produtos de Limpeza'),
('Artigos para Pets'),
('Manutenção e Reparos'),
('Limpeza e Conservação'),
('Jardinagem e Paisagismo'),
('Aulas e Reforço Escolar'),
('Cuidados com Pets'),
('Entrega e Fretes'),
('Beleza e Estética'),
('Eventos e Festas'),
('Consultoria e Assessoria'),
('Saúde e Bem-estar');